"""add product fields

Revision ID: 0869cfc49aa5
Revises: b20c6d788feb
Create Date: 2026-02-17 04:32:01.484322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0869cfc49aa5'
down_revision: Union[str, None] = 'b20c6d788feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('barcode', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('products', sa.Column('min_stock_qty', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('max_stock_qty', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('lead_time_days', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('pack_size', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_products_id', table_name='products')
    op.create_index('ix_products_tenant_barcode', 'products', ['tenant_id', 'barcode'], unique=False)
    op.create_unique_constraint('uq_products_tenant_barcode', 'products', ['tenant_id', 'barcode'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_products_tenant_barcode', 'products', type_='unique')
    op.drop_index('ix_products_tenant_barcode', table_name='products')
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'tags')
    op.drop_column('products', 'pack_size')
    op.drop_column('products', 'lead_time_days')
    op.drop_column('products', 'max_stock_qty')
    op.drop_column('products', 'min_stock_qty')
    op.drop_column('products', 'tax_rate')
    op.drop_column('products', 'price')
    op.drop_column('products', 'cost')
    op.drop_column('products', 'barcode')
    # ### end Alembic commands ###
