"""fix models

Revision ID: 187a8a64ffd5
Revises: 0869cfc49aa5
Create Date: 2026-02-17 05:09:41.063995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '187a8a64ffd5'
down_revision: Union[str, None] = '0869cfc49aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_column_mappings_dataset_type', table_name='column_mappings')
    op.drop_index('ix_column_mappings_id', table_name='column_mappings')
    op.drop_index('ix_column_mappings_name', table_name='column_mappings')
    op.create_unique_constraint('uq_column_mapping_per_tenant_name_dataset', 'column_mappings', ['tenant_id', 'name', 'dataset_type'])
    op.add_column('import_errors', sa.Column('tenant_id', sa.BigInteger(), nullable=False))
    op.alter_column('import_errors', 'message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index('ix_import_errors_id', table_name='import_errors')
    op.create_index('ix_import_errors_tenant_id_import_run_id', 'import_errors', ['tenant_id', 'import_run_id'], unique=False)
    op.create_foreign_key(None, 'import_errors', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('import_runs', 'source_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('import_runs', 'dataset_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('import_runs', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('import_runs', 'original_filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('import_runs', 'rows_total',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('import_runs', 'rows_success',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('import_runs', 'rows_failed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_import_runs_id', table_name='import_runs')
    op.drop_index('ix_inventory_snapshots_id', table_name='inventory_snapshots')
    op.create_unique_constraint('uq_inventory_snapshot_per_tenant_store_time_sku', 'inventory_snapshots', ['tenant_id', 'store_id', 'snapshot_time', 'sku'])
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index('ix_products_tenant_id', table_name='products')
    op.add_column('recommendation_feedback', sa.Column('tenant_id', sa.BigInteger(), nullable=False))
    op.drop_index('ix_recommendation_feedback_id', table_name='recommendation_feedback')
    op.create_index('ix_rec_feedback_recommendation_id', 'recommendation_feedback', ['recommendation_id'], unique=False)
    op.create_index('ix_rec_feedback_tenant_id_created_at', 'recommendation_feedback', ['tenant_id', 'created_at'], unique=False)
    op.create_foreign_key(None, 'recommendation_feedback', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('recommendations', 'explanation',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index('ix_recommendations_id', table_name='recommendations')
    op.drop_index('ix_sales_id', table_name='sales')
    op.create_unique_constraint('uq_sales_per_tenant_store_date_sku', 'sales', ['tenant_id', 'store_id', 'sale_date', 'sku'])
    op.drop_index('ix_stores_id', table_name='stores')
    op.drop_index('ix_stores_name', table_name='stores')
    op.drop_index('ix_tenants_id', table_name='tenants')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index('ix_tenants_id', 'tenants', ['id'], unique=False)
    op.create_index('ix_stores_name', 'stores', ['name'], unique=False)
    op.create_index('ix_stores_id', 'stores', ['id'], unique=False)
    op.drop_constraint('uq_sales_per_tenant_store_date_sku', 'sales', type_='unique')
    op.create_index('ix_sales_id', 'sales', ['id'], unique=False)
    op.create_index('ix_recommendations_id', 'recommendations', ['id'], unique=False)
    op.alter_column('recommendations', 'explanation',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'recommendation_feedback', type_='foreignkey')
    op.drop_index('ix_rec_feedback_tenant_id_created_at', table_name='recommendation_feedback')
    op.drop_index('ix_rec_feedback_recommendation_id', table_name='recommendation_feedback')
    op.create_index('ix_recommendation_feedback_id', 'recommendation_feedback', ['id'], unique=False)
    op.drop_column('recommendation_feedback', 'tenant_id')
    op.create_index('ix_products_tenant_id', 'products', ['tenant_id'], unique=False)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint('uq_inventory_snapshot_per_tenant_store_time_sku', 'inventory_snapshots', type_='unique')
    op.create_index('ix_inventory_snapshots_id', 'inventory_snapshots', ['id'], unique=False)
    op.create_index('ix_import_runs_id', 'import_runs', ['id'], unique=False)
    op.alter_column('import_runs', 'rows_failed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('import_runs', 'rows_success',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('import_runs', 'rows_total',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('import_runs', 'original_filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('import_runs', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('import_runs', 'dataset_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('import_runs', 'source_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'import_errors', type_='foreignkey')
    op.drop_index('ix_import_errors_tenant_id_import_run_id', table_name='import_errors')
    op.create_index('ix_import_errors_id', 'import_errors', ['id'], unique=False)
    op.alter_column('import_errors', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('import_errors', 'tenant_id')
    op.drop_constraint('uq_column_mapping_per_tenant_name_dataset', 'column_mappings', type_='unique')
    op.create_index('ix_column_mappings_name', 'column_mappings', ['name'], unique=False)
    op.create_index('ix_column_mappings_id', 'column_mappings', ['id'], unique=False)
    op.create_index('ix_column_mappings_dataset_type', 'column_mappings', ['dataset_type'], unique=False)
    # ### end Alembic commands ###
