"""Agregados auth + user

Revision ID: 5c56d4ac0fa7
Revises: 187a8a64ffd5
Create Date: 2026-02-18 18:10:11.616925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c56d4ac0fa7'
down_revision: Union[str, None] = '187a8a64ffd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
