"""add api/imports + api/inventory + api/recommendations + api/sales + api/stores

Revision ID: 780392d4a504
Revises: 4d6abbecf069
Create Date: 2026-02-21 17:25:40.559969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '780392d4a504'
down_revision: Union[str, None] = '4d6abbecf069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
