"""Arreglos de deuda tecnica

Revision ID: eaa3abf4b6e4
Revises: 5c56d4ac0fa7
Create Date: 2026-02-20 19:13:23.389492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa3abf4b6e4'
down_revision: Union[str, None] = '5c56d4ac0fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tenants_name', table_name='tenants')
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.create_index('ix_tenants_name', 'tenants', ['name'], unique=False)
    # ### end Alembic commands ###
